[server]
maxUploadSize = 200
enableCORS = false
enableXsrfProtection = true

[theme]
primaryColor = "#FFD700"
backgroundColor = "#0c0c2e"
secondaryBackgroundColor = "#1a1a3a"
textColor = "#FFFFFF"
font = "sans serif"

[browser]
gatherUsageStats = false

[runner]
magicEnabled = true
installTracer = false
fixMatplotlib = true

[logger]
level = "info"
messageFormat = "%(asctime)s %(message)s"

[deprecation]
showPyplotGlobalUse = false

[mapbox]
token = ""

[global]
developmentMode = false
logLevel = "info"
unitTest = false

# Research-specific settings
[experimental]
# Enable experimental features for research
memo = true
singleton = true