[global]
developmentMode = false

[server]
runOnSave = true
allowRunOnSave = true
port = 8501
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200

[client]
showErrorDetails = false

[theme]
primaryColor = "#4ECDC4"
backgroundColor = "#0A0E27"
secondaryBackgroundColor = "#1A1B3A" 
textColor = "#FFFFFF"
font = "sans serif"

[browser]
gatherUsageStats = false
showErrorDetails = false