[global]
developmentMode = false

[server]
runOnSave = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
showErrorDetails = true

[theme]
primaryColor = "#FFD700"
backgroundColor = "#0c0c2e"
secondaryBackgroundColor = "#1a1a3a"
textColor = "#FFFFFF"
font = "sans serif"

[client]
showErrorDetails = true

[logger]
level = "info"